name: Generate Snake Animation

# Controls when the action will run
on:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

# The jobs that this workflow will run
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository's code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Generate the snake animation
      - name: Generate Snake animation
        uses: Platane/snk@v2.2.1
        with:
          # github_user_name is your GitHub username (replace YOUR_GITHUB_USERNAME)
          github_user_name: YOUR_GITHUB_USERNAME
          # Output the SVG file to the images directory
          outputs: dist/snake.svg

      # Step 3: Commit and push the animation to the repository
      - name: Commit and push the snake animation
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/snake.svg
          git commit -m "chore: updated the snake animation"
          git push

      # Step 4: Optionally, upload the animation as a GitHub artifact (if you want to store it)
      - name: Upload Snake SVG Artifact
        uses: actions/upload-artifact@v3
        with:
          name: snake-svg
          path: dist/snake.svg
